name: feature-push

on:
  push:
    branches: [ feature/*, features/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup dependencies
        run: npm install
      
      - name: Test with 'jest'
        run: npm test
